blank_issues_enabled: false
contact_links:
  - name: â“ StackOverflow
    url: https://stackoverflow.com/questions/tagged/popper.js
    about: Having troubles with Popper? Ask to the awesome SO community!
  - name: ğŸ’¬ Spectrum
    url: https://spectrum.chat/popper-js
    about: Want to talk about Popper with other users? Join us on Spectrum!
