name: Release Floating UI

on:
  repository_dispatch:
    types: [rollingversions_publish_approved]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/typescript
      - uses: ./.github/actions/unit
      - uses: ./.github/actions/functional

  publish:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm run build:typescript
      - run: npx rollingversions publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
